import type { FishDefinition } from "./types";

export const GAME_CONFIG = {
  match: {
    countdownSeconds: 3,
    timedDurationSeconds: 60,
  },
  bar: {
    height: 0.24,
    gravity: 1.82,
    liftAcceleration: 3.34,
    velocityDamping: 1.55,
    maxRiseSpeed: 0.86,
    maxFallSpeed: 0.74,
    topBounce: 0.16,
    bottomBounce: 0.3,
  },
  catch: {
    initialProgress: 0.5,
    gainPerSecond: 0.22,
    lossPerSecond: 0.11,
    panicThreshold: 0.76,
    panicMultiplier: 1.28,
  },
  round: {
    caughtDisplaySeconds: 1.05,
    escapedDisplaySeconds: 0.9,
  },
  simulation: {
    maxDeltaSeconds: 0.04,
    fishEdgePadding: 0.035,
  },
  cooperative: {
    zone: {
      width: 0.22,
      height: 0.22,
    },
    horizontal: {
      heldAcceleration: 1.7,
      releasedAcceleration: -1.7,
      velocityDamping: 1.7,
      maxSpeed: 0.7,
      edgeBounce: 0.24,
    },
  },
} as const;

export const FISH_DEFINITIONS: readonly FishDefinition[] = [
  {
    id: "carp",
    name: "Carp",
    symbol: "●",
    difficulty: "Easy",
    score: 10,
    color: "#f1c36d",
    agility: 3.2,
    jitter: 0.08,
    damping: 4.8,
    maxSpeed: 0.28,
    targetMinSeconds: 1.25,
    targetMaxSeconds: 2.1,
    dartRate: 0.08,
    dartForce: 0.1,
    baseWeight: 0.42,
  },
  {
    id: "bass",
    name: "Bass",
    symbol: "◆",
    difficulty: "Medium",
    score: 25,
    color: "#8fd3a9",
    agility: 4.4,
    jitter: 0.17,
    damping: 4.25,
    maxSpeed: 0.4,
    targetMinSeconds: 0.8,
    targetMaxSeconds: 1.45,
    dartRate: 0.18,
    dartForce: 0.16,
    baseWeight: 0.3,
  },
  {
    id: "catfish",
    name: "Catfish",
    symbol: "▲",
    difficulty: "Hard",
    score: 50,
    color: "#e78c72",
    agility: 5.5,
    jitter: 0.3,
    damping: 3.7,
    maxSpeed: 0.56,
    targetMinSeconds: 0.46,
    targetMaxSeconds: 1,
    dartRate: 0.34,
    dartForce: 0.24,
    baseWeight: 0.19,
  },
  {
    id: "squid",
    name: "Squid",
    symbol: "✦",
    difficulty: "Extreme",
    score: 100,
    color: "#c99cff",
    agility: 7,
    jitter: 0.5,
    damping: 3.15,
    maxSpeed: 0.74,
    targetMinSeconds: 0.24,
    targetMaxSeconds: 0.68,
    dartRate: 0.62,
    dartForce: 0.34,
    baseWeight: 0.09,
  },
] as const;
